branch-defaults:
  master:
    environment: dev-env
    group_suffix: null
global:
  application_name: coastviewer
  branch: null
  default_platform: Docker 17.03.1-ce
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
